### ISSUE TITLE
Update usage of pandas.np

### ISSUE THREAD

**Issue by christiemj09** [anhaidgroup/py_entitymatching#135]
Using Numpy referenced through Pandas raises a `FutureWarning` advising to import and use Numpy directly instead. Update existing usage of `pandas.np` to use `numpy` directly in order to prevent future dependency-based errors.

**Comment by fventuri-availity** [comment]
I just created a PR for this change: https://github.com/anhaidgroup/py_entitymatching/pull/142

Franco

**Comment by pavan-kalyan** [comment]
I see that the PR for this has been merged, can this issue be resolved/closed?
Are there any pending changes for this issue still?

**Comment by christiemj09** [comment]
Ah yes, this issue has been resolved; closing now.
