### ISSUE TITLE
Typo (lack of a right parenthesis) on the API docstring

### ISSUE THREAD

**Issue by ciuji** [anhaidgroup/py_entitymatching#150]
https://github.com/anhaidgroup/py_entitymatching/blob/4fa644cc61f39288a69724b09ff5a6ec4f685b27/py_entitymatching/blocker/rule_based_blocker.py#L653

Dear them,

I found that there exists a simple typo on the code API docstring.

The right sentence should be `D = rb.block_tuples(A.loc[0], B.loc[1])`

**Comment by christiemj09** [comment]
Fixed in accd158; thanks @ciuji!
