### ISSUE TITLE
[Overlap blocker] The token "of" is not included in the stop_words set

### ISSUE THREAD

**Issue by mathgeek404** [anhaidgroup/py_entitymatching#44]
I'm from CS638, we have been working on our project stage 4 using Magellan. Many of the existing stop words such as "the", "and", etc were common across multiple strings we used for blocking (particularly from board game titles). The rem_stop_words code managed to prune these from the calculations of overlap, thus reducing our false positives greatly. 

However, many tuple pairs were formed with strings (board game titles) sharing the token"of". Perhaps "of" can be added this this almost extensive list of stop_words?

**Comment by kvpradap** [comment]
This can be updated by the user directly.
