### ISSUE TITLE
[Bug][OverlapBlocker] rem_stop_words attribute to block_candset, block_tables not working

### ISSUE THREAD

**Issue by mathgeek404** [anhaidgroup/py_entitymatching#46]
Another issue to share from an annoying CS638 student. Slightly more pressing

When using the OverlapBlocker class, we noticed the  _rem_stop_words_ attribute in block_candset():
` rem_stop_words (boolean): A flag to indicate whether stop words
                                      (e.g., a, an, the) should be removed
                                      from the token sets of the overlap
                                      attribute values (defaults to False).`

 However, we noticed that, by default and regardless of the attribute's value ("rem_stop_words=False" or "rem_stop_words=True"), this process runs regardless, always pruning these stop words from the token sets. 

Upon inspection, it looks like the _rem_stop_words_ attribute is passed down but never used. In particular, the stop word pruning seems to occur here, regardless of the attribute's value. 

https://github.com/anhaidgroup/py_entitymatching/blob/master/py_entitymatching/blocker/overlap_blocker.py#L584-L586

And:

https://github.com/anhaidgroup/py_entitymatching/blob/master/py_entitymatching/blocker/overlap_blocker.py#L601-L604

Perhaps an if statement or something should be used here to conditionally apply this "stop word pruning"?

**Comment by kvpradap** [comment]
This will be handled in the next release.
