### ISSUE TITLE
Link to project homepage in README.md wrong

### ISSUE THREAD

**Issue by aardila** [anhaidgroup/py_entitymatching#51]
The [current link](https://sites.google.com/site/anhaidgroup/projects/py_entitymatching) under Important Links > Project Homepage points to a _"Page not found"_ page. If I'm not mistaken, the correct link should be https://sites.google.com/site/anhaidgroup/projects/magellan/py_entitymatching

**Comment by kvpradap** [comment]
Thanks for the note.

I updated the links. Now you should see the correct links in the main page.
