### ISSUE TITLE
Broken link in py_entitymatching/v0.1.x/user_manual/installation.html

### ISSUE THREAD

**Issue by aardila** [anhaidgroup/py_entitymatching#52]
> **Installing from Source Distribution**
> Download the py_entitymatching package from [here](https://sites.google.com/site/anhaidgroup/projects/py_entitymatching)

**Comment by kvpradap** [comment]
Thanks for the note.

I have fixed the link. Let me know if you face any issues.

**Comment by aardila** [comment]
Now it just points to the project home page. The context of the link is that it would download the pt_entitymatching package or at least take me somewhere where it can be downloaded from...

**Comment by kvpradap** [comment]
The idea is to point to homepage and let the user download different package types (zip/gz) depending on his/her need. 

On a side note, just curious to know what is your specific need to install from source rather than conda?

**Comment by aardila** [comment]
Whether to point the user to a page chuck-full of text where they would need to parse the whole page to determine where the download link is, is definitely up to you ;)

Neither conda or pip worked on university workstations.

**Comment by kvpradap** [comment]
Interesting. 

I am going to leave the download link as is at this point and will revisit if this creates more confusion.
